# Properties active for ALL profiles:
---
# This 'name' of our application is important
# as the config server typically has to serve up properties for many applictions:
spring:
  config:
    import: optional:configserver:http://localhost:8001 # Where should we call the config server at?
  profiles:
    active: prod
  application:
    name: client-app # What set of properties will we ask the config server for?

server:
  port: 8002 # What port should we expose for our web interface

# Uncomment these lines to activate "northamerica" as the active profile.
# Ordinarily we would not activate a profile from within a property file, but this is just a demo:
#---
#spring:
#  profiles:
#    active: northamerica